# Generated by Django 4.2.3 on 2023-07-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restricted',
            field=models.BooleanField(default=True),
        ),
    ]
