# Generated by Django 4.2.3 on 2023-08-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_options_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_provider',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('GOOGLE', 'GOOGLE')], default='EMAIL', max_length=50),
        ),
    ]
