# Generated by Django 4.2.3 on 2023-07-30 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_post_picture_alter_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Picture',
            field=models.FileField(blank=True, null=True, upload_to='Images_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
        ),
    ]
