# Generated by Django 4.2.3 on 2023-07-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='song',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
